server:
  port: 8082

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/network_portal
    username: abhishek
    password: Abhi@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration: ${SECURITY_JWT_EXPIRATION}

workers:
  python-path: python3
  ping-script-path: /home/abhishek/Projects/Network-test-portal/python-workers/ping_worker.py
  iperf-script-path: /home/abhishek/Projects/Network-test-portal/python-workers/iperf_worker.py
  timeout-seconds: 30
