server:
  port: 8082

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration: ${SECURITY_JWT_EXPIRATION}

workers:
  python-path: ${WORKERS_PYTHON_PATH}
  ping-script-path: ${WORKERS_PING_SCRIPT_PATH}
  iperf-script-path: ${WORKERS_IPERF_SCRIPT_PATH}
  timeout-seconds: ${WORKERS_TIMEOUT_SECONDS}
